[package]
name = "oxybox"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
native-tls = "0.2"
tokio-native-tls = "0.3"
x509-parser = "0.17"
url = "2"
