demo:
  organisation_id: demo
  polling_interval_seconds: 10
  targets:
    - url: https://www.google.com
    - url: https://www.github.com
      accepted_status_codes: [200, 301]
    - url: https://grafana.com/

organisationX:
  organisation_id: another-org
  polling_interval_seconds: 20
  targets:
    - url: http://www.example.com
